<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        h1, h2, h3 { text-align: center; margin: 0; padding: 5px; }
        h2 { margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 25px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; }
        .status-section { page-break-inside: avoid; }
        .in_stock h2 { color: green; }
        .low_stock h2 { color: orange; }
        .out_of_stock h2 { color: red; }
        .pre_order h2 { color: blue; }
        .footer { text-align: center; font-size: 10px; margin-top: 20px; color: #666; }
    </style>
</head>
<body>
    <h1>Inventory Report</h1>
    <p style="text-align:center;">Generated on {{ now()->format('F d, Y h:i A') }}</p>

    @php
        $statusLabels = [
            'in_stock' => 'In Stock',
            'low_stock' => 'Low Stock',
            'out_of_stock' => 'Out of Stock',
            'pre_order' => 'Pre-Order',
        ];
    @endphp

    @foreach ($statusLabels as $status => $label)
        @if(isset($groupedProducts[$status]) && $groupedProducts[$status]->count())
        <div class="status-section {{ $status }}">
            <h2>{{ $label }}</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Brand</th>
                        <th>Variants</th>
                        <th>Total Stock</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($groupedProducts[$status] as $index => $product)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->category->name ?? 'N/A' }}</td>
                            <td>{{ $product->brand->name ?? 'N/A' }}</td>
                            <td>
                                @foreach ($product->variants as $variant)
                                    • {{ $variant->size ?? 'N/A' }} /
                                    {{ $variant->colorway ?? 'N/A' }} :
                                    {{ $variant->stock_quantity }} <br>
                                @endforeach
                            </td>
                            <td>{{ $product->total_stock_quantity }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
    @endforeach

    <div class="footer">
        <p>Generated by FlipMarket System | {{ now()->format('Y') }}</p>
    </div>
</body>
</html>
