<?php

namespace App\Exports\Sheets;

use App\Models\Product;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class InventoryReportSheet implements FromArray, WithTitle, WithStyles, WithColumnWidths
{
    protected $groupedProducts;

    public function __construct()
    {
        // Fetch all products with variants, category, and brand, grouped by stock status
        $this->groupedProducts = Product::with(['variants', 'category', 'brand'])
            ->orderBy('name')
            ->get()
            ->groupBy(fn($p) => $p->status);
    }

    public function title(): string
    {
        return 'Inventory Report';
    }

    public function array(): array
    {
        $rows = [
            ['FLIP MARKET'],
            ['Inventory Report'],
            ['Generated on: ' . now()->format('F d, Y h:i A')],
            [''],
        ];

        $statusLabels = [
            'in_stock' => 'In Stock',
            'low_stock' => 'Low Stock',
            'out_of_stock' => 'Out of Stock',
            'pre_order' => 'Pre-Order',
        ];

        foreach ($statusLabels as $status => $label) {
            if (!isset($this->groupedProducts[$status])) continue;

            $rows[] = [$label]; // status header
            $rows[] = ['#', 'Product', 'Category', 'Brand', 'Variants', 'Total Stock'];

            foreach ($this->groupedProducts[$status] as $index => $product) {
                $variantText = collect($product->variants)->map(function ($variant) {
                    return ($variant->size ?? 'N/A') . ' / ' . ($variant->colorway ?? 'N/A') . ' : ' . $variant->stock_quantity;
                })->implode("\n");

                $rows[] = [
                    $index + 1,
                    $product->name,
                    $product->category->name ?? 'N/A',
                    $product->brand->name ?? 'N/A',
                    $variantText,
                    $product->total_stock_quantity,
                ];
            }

            $rows[] = ['']; // empty row for spacing
        }

        $rows[] = ['Generated by FlipMarket System | ' . now()->format('Y')];

        return $rows;
    }

    public function columnWidths(): array
    {
        return [
            'A' => 5,
            'B' => 30,
            'C' => 20,
            'D' => 20,
            'E' => 40,
            'F' => 15,
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        $sheet->getStyle('A1:F1')->getFont()->setBold(true)->setSize(16);
        $sheet->getStyle('A2:F2')->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A3:F3')->getFont()->setSize(10)->getColor()->setRGB('6B7280');
        
        $highestRow = $sheet->getHighestRow();
        $sheet->getStyle("A5:F{$highestRow}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

        $sheet->getStyle('E5:E'.$highestRow)->getAlignment()->setWrapText(true);
        $sheet->getStyle('A5:F'.$highestRow)->getAlignment()->setVertical(Alignment::VERTICAL_TOP);

        return [];
    }
}
